language: node_js
dist: bionic
sudo: true
before_script:
  - sleep 20
node_js:
  - "8"
  - "10"
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.2.deb && sudo dpkg -i --force-confnew elasticsearch-6.6.2.deb && sudo systemctl start elasticsearch.service
notifications:
  email:
    recipients:
      - claude.niederlender@inist.fr
      - remy.meja@inist.fr
      - conditordev@gmail.com
    on_success: change
on_failure: always