language: node_js
sudo: true
addons:
  apt:
    packages:
      - openjdk-8-jdk
before_script:
  - sleep 10
node_js:
  - "8"
  - "10"
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.2.deb && sudo dpkg -i --force-confnew elasticsearch-6.6.2.deb && sudo systemctl start elasticsearch.service && sudo systemctl enable elasticsearch.service
notifications:
  email:
    recipients:
      - claude.niederlender@inist.fr
      - remy.meja@inist.fr
      - conditordev@gmail.com
    on_success: change
on_failure: always